### ISSUE TITLE
stanzas spécifiques seulement?

### ISSUE THREAD

**Issue by nicomq** [ezproxy-config/french#16]
J'ai une question à propos du commit sur les Licences Nationales : commit 0520864dd4f7d2a3c74350a19756536bcd9157fc.

Le point de départ de ce dépôt, dans mon souvenir, c'était de suivre les config *spécifiques* qui n'étaient pas suivies dans la DB d'OCLC à https://www.oclc.org/support/services/ezproxy/documentation/db.en.html
C'est ce que dit le README du dépôt, peut-être de façon insuffisamment claire : "Configuration EzProxy pour les bases françaises", avec renvoi à OCLC pour le reste.

Dans le commit des LN, je vois plein de choses qui sont déjà suivies par OCLC. Par ex. Sage, Emeral Insight, etc. Les fichiers commités a priori sont indentiques à ceux d'OCLC. Je comprendrais si c'était une config spécifique aux licences nationales françaises, mais ça n'a pas l'air d'être le cas.

Je propose de supprimer ces fichiers LN, quand ils sont d'ores et déjà couverts à l'identique par OCLC, et de modifier le README pour rendre cette logique plus claire.

N.

**Comment by symac** [comment]
@nicomq j'avoue avoir validé assez rapidement le commit dont tu parles. La suggestion de se limiter à ce qui est différent / absent d'OCLC me semble en effet correspondre aux discussions à l'origine de ce dépôt. Si tu veux/peux t'occuper de vérifier les différentes n'hésite pas à faire une pull request, sinon j'essaierai de m'en occuper un de ces jours.

**Comment by nicomq** [comment]
fait les pull requests correspondantes
